### ISSUE TITLE
wHats tHis?

### ISSUE THREAD

**Issue by kenrick** [hellosputnik/Qtic-Qtac-Qtoe#1]
🃏

**Comment by hellosputnik** [comment]
Hi Kenrick,

Thank you for your interest in this project. Qtic-Qtac-Qtoe is a simple implementation of the classic Tic-Tac-Toe game made in C++ using the Qt cross-platform application framework to demonstrate the powerful features of the Qt Framework.

**Comment by hellosputnik** [comment]
We have a lot features currently in development:

- Colored Os and Xs
- 2-player Mode
- Vs. AI
- High Score Board

Please stay tuned for updates. These exciting features should be available soon!
